### ISSUE TITLE
Force lexer/parser build sequence

### ISSUE THREAD

**Issue by ericvergnaud** [antlr4ide/antlr4ide#101]
Currently, on each startup/clean, all the grammars get rebuilt in a non deterministic order.
This leads to false errors such as token file not found, and a bunch of warnings for illegal implicit tokens in pure parsers.
It would be nice to ensure that background builds process lexer files before parser ones

**Comment by jknack** [comment]
similar comment here, not sure this is supported by Xtext :(

**Comment by KristofSzabados** [comment]
Would it be possible for us to tell the dependencies of a g4 file manually (as a property).

This info could be used to create a dependency graph of g4 files, that could be used to find the best build order.

**Comment by HSorensen** [comment]
What kind of dependencies do you have?

Henrik

**Comment by arifogel** [comment]
My workaround for this is to uncheck "tool is activated", and do all building with ant. See the lexer and parser building code in https://github.com/arifogel/batfish/master/projects/batfish/build.xml
