### ISSUE TITLE
Build error?

### ISSUE THREAD

**Issue by ekrisza** [antlr4ide/antlr4ide#115]
I"m trying to build antlr4ide using maven, following the guide.
after issuing "mvn clean package"

But I get several errors starting with this:
"
     [exec] error(206): /C:\Users\ekrisza\github\antlr4ide\antlr4ide.core/src/generated/java/com/github/jknack/antlr4ide/parser/antlr/lexer/InternalAntlr4Lexer.g:130:23: Alternative 2: after matching input such as '[''[''\'']''"''[''\''"''[''\''"''"''[''"''"''"''\'''"''\'''\'']''\'''"''\'']''\'''[''"''\'''\'''\'']''\'''\'']''\'''[''"''\'''"''"''\'']''\''\''\'']''\'''"''\'']''"''\'''\'''\'']''\'''\'']''\'''[''\'''\'']''\''\''\''"''"''[''"''\'']''\''\''\'']''\'''\'']''"''\'']''"''[''\'']''\'']''"''[''\'''\'''\'''\'']''\'''\'']''\'''[''\'''\'']''\''\''\'']''\'''\'']''"''\'''"''\'']''\''\''\'']''\'''[''"''"''"''\'']''"''\'']''"''\'']''"''[''"''\'']''\'']''"''\'']''\'']''"''[''\''\''\'']''\'']''"''[''\'']''"''\'''[''\''\''\''\'''\'']''\'''\'']''"''\'''\'']''"''[''\'']''\'''\'']''\'''\'']''"''[''\''\''\'']''\'']''"''[''\'']''\'''\'']''\'''\''[''[''\'']''"''\''"''"''[''\''"''"''\''"''[''"''"''"''\'']''"''"''\'']''"''\'']''\'']''"''[''"''\'']''\'']''"''\'']''\'']''"''\'']''"''[''\'']''\'']''"''\''[''"''[''\''"''\'''\''\'''\'''[''"''"''"''\'']''\'''\'']''\'''[''"''\'']''\'']''\'']''"''\'''\'''\'']''\'''\'']''\'''[''\'''\'']''\''\''\'']''\'''\'']''[''\'']''\'''\'']''\''\''\'']''\''\''\'']''\''\''\''"''[''\'''[''"''"''"''\'']''"''\'']''"''[''"''\'']''\'']''"''\'']''"''\'']''"''[''\'']''\'']''"''[''\''\''\''\'''"''[''\'''\'''\'']''\'''\'''\'''\'']''\'''\'']''\'''[''\'''\'']''\''\''\'']''\'''\'']''\'']''\'']''\'']''"''\'']''[''[''"''"''\'''"''"''\'']''\''\''\'']''\''\''\'']''\'''"''\'''\'''\'']''\'''\'']''\'''[''\'''\'']''\''\''\'']''\'''\'']''[''\'']''\'''\'']''\'''\'']''[''\'']''\'''\'']''"''"''"''\'''"''"''\'']''\''\''\'']''\''\''\'']''\'''\'''"''\'']''\''\''\'']''\''\''\'']''\'''"''\'''"''\'''\'']''\'''\'']''\'']''\''\''\'']''\'''[''\'']''\'']''[''\'']''\'']''"''"''\'']''[''"''\'''\'''\'']''\'''\'']''\'''[''\'''\'''\'''\'']''\'''\'']''\'''\'']''\'''[''\'''\'']''\''\''\'']''\'''\'']''\'']''[''\'']''\'''\'']''"''\'''\'']''\''\''\'']''\''\''\'']''\'''\'''\'''\'']''\'''\'']''\'']''\''\''\'']''\''\''\'']''\'''[''"''"''"''\'']''[''"''\'']''[''"''\'''"''\'''\'']''\'''\'']''\''\''\'']''\''\''\'']''\'''[''\'']''\'']''[''\'']''\'']''"''\'']''[''"''\'']''[''"''\'''"''"''\'']''\'''\'']''[''"''"''"''\'']''\'''\'']''\'''[''\'']''\'']''\'']''\'']''"''\'''\'''\'']''\'''\'']''\'''[''\'''\'']''\''\''\'']''\'''\'']''[''\'']''\'''\'']''\'''\'']''\'''\'']''\'''[''\'']''\''[''[''"''\'']''"''\'']''\'']''\'']''\'']''"''"''\''"''"''[''\'''"''\'']''\''\''\'']''\''\''\'']''\''\''\'']''\'''\'']''"''\'']''\'']''\'']''\'']''"''\'']''[''[''"''\'']''"''\'']''\'''\'']''\''\''\'']''\''\''\'']''\''\''\''"''\'''"''[''"''\'']''\''\''\'']''\''\''\'']''\''\''\'']''\'''[''"''\'']''\'']''[''\'']''\'']''"''\'']''\'''\''\'''\'''[''"''"''"''\'']''\'''[''"''\'''\'']''\''\''\'']''\''\''\'']''\''\''\'']''\''\''\''"''\'''\'']''\''\''\''"''\'']''\''\''\'']''\''\''\'']''\'''\'''\'''\'']''\''\''\''"''\'']''\''\''\'']''\''\''\'']''\'''\'']''\''\''\'']''\'']''\'']''\''\''\''\'''[''\''\''\''\'''\'''[''\''\''\''[''\'']''[''\'''\'']''"''\'']''\''\''\'']''\''\''\'']''\'''\'''\'''\'']''\'''\'']''\'']''\''\''\'']''\''\''\'']''\'''[''\'''"''\'']''\''\''\'']''\''\''\'']''\''\''\'']''\''\''\'{'\u0000'..'\t', '\u000B'..'\f', '\u000E'..'!', '#'..'&', '('..'[', ']'..'\uFFFF'}'"''\'''\'']''\'''\'']''\'']''\''\''\'']''\''\''\'']''\'''\'''\''\'''\'''[''"''"''\'']''\'''"''\'']''\'']''\''\''\'']''\''\''\''[''\'''[''"''\'']''\'']''[''\'']''\'']''"''"''"''\'']''[''"''\'']''[''"''\'']''"''\'']''\'']''\'']''"''\'']''[''\'']''"''\'']''"''\'']''\'']''\'''[''\'']''\'''\''\'''[''\'']''"''[''\''"''"''\''\''\'']''\'''[''\''"''"''[''\'''\'']''\''\''\'']''\''\''\'']''\'''\'''\'''\'']''\''\''\''"''"''[''"''\'']''"''\'']''\'']''\''\''\'']''\'''\'']''\''\''\'']''\'']''\'']''\''\''\''\'''[''\''\''\''\'''\'']''\'']''\''\''\'{'\u0000'..'\t', '\u000B'..'\f', '\u000E'..'!', '#'..'&', '('..'[', ']'..'\uFFFF'}'\'''[''\''\''\'']''\'']''\''[''"''[''\'''\'''\'']''\'''\'''\'''\'']''\'''\'']''\'''[''\'''\'']''\''\''\'']''\'''\'']''\'']''\'']''\'']''"''\''\''\'']''\''[''\'''[''\'']''\'']''\'']''\'''\'''\''\'''[''\'']''"''\''"''"''\'''[''\''\''\''\'''\''\'''\'''[''\'''\'']''\''\''\'']''\''\''\''"''\''\''\''"''"''[''\'''\'']''\'']''\''\''\'']''\''\''\''[''\''\''\'']''[''"''\'''[''\'']''\'''\'']''\''\''\''"''\''\''\'']''\''\''\'']''\''\''\'{'\u0000'..'\t', '\u000B'..'\f', '\u000E'..'!', '#'..'&', '('..'[', ']'..'\uFFFF'}'"''[''\''\''\'']''\''\''\'']''\''\''\''[''\''\''\'']''[''[''\'''[''"''"''\'']''\''\''\''"''\'']''\''\''\'']''\''\''\'']''\'''[''"''\'''\'''\'']''\'''\'']''\'''[''[' decision cannot predict what comes next due to recursion overflow to RULE_ARG_ACTION from RULE_ARG_ACTION
"

Which is cusing several others like these:
"     [exec] error(3):  cannot find tokens file C:\Users\ekrisza\github\antlr4ide\antlr4ide.core\src\generated\java\com\github\jknack\antlr4ide\parser\antlr\internal\InternalAntlr4Lexer.tokens"
"     [exec]     org.eclipse.emf.common.util.WrappedException: java.io.FileNotFoundException: C:\Users\ekrisza\github\antlr4ide\antlr4ide.core\src\generated\java\com\github\jknack\antlr4ide\parser\antlr\lexer\InternalAntlr4Lexer.java (The system cannot find the file specified)"

What could i be doing wrong?

**Comment by kozchris** [comment]
Did you figure this issue out?

**Comment by ekrisza** [comment]
sadly not.

**Comment by arifogel** [comment]
I noticed you are using Windows. I would like to point out that you can realistically only build this project with Java 7 at this point. Is that what you were using? Does this happen with the latest master?

**Comment by HSorensen** [comment]
As a data-point, I am using Java 8 jdk and Eclipse Neon.1 on Windows 10 for my development and build of antlr4ide. Seems to work really well here.

**Comment by HSorensen** [comment]
@ekrisza Please retry the build with current git version. I am closing this for now, but please reopen if the error still persists with latest git version.
