### ISSUE TITLE
Java 

### ISSUE THREAD

**Issue by daw3rd** [antlr4ide/antlr4ide#132]
I'm using Eclipse Luna on Windows 7 and have installed the ide from the marketplace.  When I right-click on the .g4 file and select Run As-> Generate ANTLR Recognizer, I get the following

Tool v4.4 (C:\Users\IBM_AD~1\AppData\Local\Temp\antlr-4.4-complete.jar)
Sqore2.g4 -o C:\dev\eclipse-ws\quantum\jaq-core\target\generated-sources\antlr4\com\ibm\research\jaq\sqore2\parser\antlr -listener -no-visitor -package com.ibm.research.jaq.sqore2.parser.antlr -encoding UTF-8
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

BUILD SUCCESSFUL
Total time: 365 millisecond(s)

When I execute from the command line it works fine

C:\dev\eclipse-ws\quantum\jaq-core>env | grep -i java
JAVA_HOME=C:\dev\Java\jdk1.8.0_51_oracle\
PATH=/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/dev/Java/jdk1.8.0_51_oracle/bin:/cygdrive/c/Program Files/
Common Files/Microsoft Shared/Windows Live:/cygdrive/c/Program Files (x86)/Common Files/Microsoft Shared/Windows Live:/B
IN:/USR/BIN:/cygdrive/c/Windows/SYSTEM32:/cygdrive/c/Windows:/cygdrive/c/Windows/SYSTEM32/WBEM:/cygdrive/c/Windows/SYSTE
M32/WINDOWSPOWERSHELL/V1.0:/cygdrive/c/PROGRAM FILES/IBM/INFOPRINT SELECT:/cygdrive/c/PROGRAM FILES (X86)/IBM/PERSONAL C
OMMUNICATIONS:/cygdrive/c/PROGRAM FILES (X86)/IBM/TRACE FACILITY:/cygdrive/c/PROGRAM FILES/SLIKSVN/BIN:/cygdrive/c/SWTOO
LS/READYAPPS:/cygdrive/c/PROGRAM FILES (X86)/INTEL/OPENCL SDK/2.0/BIN/X86:/cygdrive/c/PROGRAM FILES (X86)/INTEL/OPENCL S
DK/2.0/BIN/X64:/cygdrive/c/DEV/DSM/BIN:/cygdrive/c/PROGRAM FILES/INTEL/WIFI/BIN:/cygdrive/c/PROGRAM FILES/COMMON FILES/I
NTEL/WIRELESSCOMMON:/cygdrive/c/PROGRAM FILES (X86)/INTEL/SERVICES/IPT:/cygdrive/c/Program Files/ThinkPad/Bluetooth Soft
ware:/cygdrive/c/Program Files/ThinkPad/Bluetooth Software/syswow64:/cygdrive/c/dev/Rational/common:/cygdrive/c/Program
Files (x86)/Intel/OpenCL SDK/2.0/bin/x86:/cygdrive/c/Program Files (x86)/Intel/OpenCL SDK/2.0/bin/x64:/cygdrive/c/Progra
m Files (x86)/Bitvise SSH Client:/cygdrive/c/Program Files/doxygen/bin:/cygdrive/c/Program Files (x86)/Common Files/HP/D
igital Imaging/bin:/cygdrive/c/Program Files (x86)/HP/Digital Imaging/bin:/cygdrive/c/Program Files (x86)/HP/Digital Ima
ging/bin/Qt/Qt 4.3.3:/cygdrive/c/dev/CloudFoundry:/cygdrive/c/dev/apache-maven-3.2.2/bin:/cygdrive/c/Program Files (x86)
/IBM/Mobility Client:/cygdrive/c/Program Files (x86)/Windows Live/Shared:/cygdrive/c/dev/nodejs:/cygdrive/c/Program File
s (x86)/OpenVPN/bin:/cygdrive/c/Program Files/Mercurial:/cygdrive/c/Program Files/Intel/WiFi/bin:/cygdrive/c/Program Fil
es/Common Files/Intel/WirelessCommon:/cygdrive/c/Users/IBM_ADMIN/AppData/Roaming/npm

C:\dev\eclipse-ws\quantum\jaq-core>doit

C:\dev\eclipse-ws\quantum\jaq-core>java -jar C:\Users\IBM_AD~1\AppData\Local\Temp\antlr-4.4-complete.jar src/main/java/c
om/ibm/research/jaq/sqore2/parser/antlr/Sqore2.g4 -o src/main/java/com/ibm/research/jaq/sqore2/parser/antlr -listener -n
o-visitor -package com.ibm.research.jaq.sqore2.parser.antlr -encoding UTF-8

C:\dev\eclipse-ws\quantum\jaq-core>

**Comment by arifogel** [comment]
I just picked up this project. Is this still an issue? Please try again with the latest version of antlr supported by this tool. Otherwise I will close as invalid in two weeks.

**Comment by HSorensen** [comment]
No feedback provided. Closing this one.
