### ISSUE TITLE
where are examples?

### ISSUE THREAD

**Issue by paulvi** [antlr4ide/antlr4ide#141]
Please tell where to take those grammar examples as on screen

![](http://www.antlr.org/images/eclipse-v4-plugin.png)

**Comment by xoxota99** [comment]
https://github.com/antlr/grammars-v4

**Comment by arifogel** [comment]
I'm trying to clean up the issues page. If there is nothing outstanding, let me know so I can close this. Otherwise will close as invalid in two weeks.

**Comment by timeraider4u** [comment]
+1 for closing.

anyway, maybe we can remember to place the link into the README.MD or the wiki-pages later ;-).
