### ISSUE TITLE
-lib option missing

### ISSUE THREAD

**Issue by marcpawl** [antlr4ide/antlr4ide#145]
My project is diveded into different directories with common items being imported.
The properties for the project under ATLR4/Tool has no provision for the lib option to import the different files.

**Comment by arifogel** [comment]
Can you be more specific? What are you trying to accomplish? What lib option? Is this an argument that is supposed to be passed to the antlr4 jar?

**Comment by HSorensen** [comment]
From the antlr manual:
ANTLR Tool Command-Line Options
-lib libdir
When looking for .tokens files and imported grammars, ANTLR normally
looks in the current directory. This option specifies which directory to
look in instead.

**Comment by HSorensen** [comment]
close this bug.
