### ISSUE TITLE
Future home of antlr4ide

### ISSUE THREAD

**Issue by arifogel** [antlr4ide/antlr4ide#157]
@timeraider4u suggested in pull request #127 that we move antlr4ide to a community project. I agree. In order to keep the remaining issues and webhooks, etc., we should:
1. Create a github organization, say "antlr4ide-org" or something like that.
2. Make @jknack an admin
3. @jknack will have to transfer this repository to the "antlr4ide-org" organization.
At that point, @jknack will not have to do any more work. I already control the marketplace release of antlr4ide with the repository at <https://github.com/arifogel/antlr4ide-eclipse-release>. I could also move this repository to the new organization, so we can share control of release management.

If anyone objects, this is the place to do it. If you'd like to be an admin, please say so here.
To begin with, I nominate myself @arifogel, @timeraider4u, and @HSorensen.

**Comment by HSorensen** [comment]
+1.
I think this is a good idea. 
ANTLR4IDE definitely deserves a future and we owe @jknack gratitude for creating this in the first place!

**Comment by timeraider4u** [comment]
:+1:

**Comment by arifogel** [comment]
OK I created the organization "antlr4ide" and invited you two and @jknack. I also moved the release repository over there, and updated the marketplace pointer. Users should not notice the difference.

The only remaining step is for @jknack to transfer ownership of this repo to the "antlr4ide" organization if he is willing.
According to https://help.github.com/articles/about-repository-transfers/ the transfer should be seamless.
Specifically:

> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line: `git remote set-url origin new_url`

**Comment by HSorensen** [comment]
Nick, do we need the "4" in the name ?

**Comment by arifogel** [comment]
It's done!

**Comment by arifogel** [comment]
Uh @HSorensen and @timeraider4u please accept your invites so I can give you the appropriate privileges.

**Comment by timeraider4u** [comment]
Thx! I have accepted your invitation.

**Comment by HSorensen** [comment]
@arifogel I just created a pull request #158, but I did not see the automated testing kick in. Are there some references to the jknack still ?
