### ISSUE TITLE
Discussion on using of Xtend

### ISSUE THREAD

**Issue by timeraider4u** [antlr4ide/antlr4ide#162]
Dear all, I would like to hear your opinion on usage of [http://www.eclipse.org/xtend/documentation/](Xtend) (not to be confused with Xtext) files inside of Antlr4IDE. Basically Xtend is a kind of domain-specific language (DSL) for programming. Xtend uses a Java-like syntax/grammar and the files themselves are translated into Java files (this is done automatically by a generator of the Xtend Eclipse plug-in). Personally, I love the idea of DSLs but I hate Xtend for a couple of reasons. I would say that for an experienced Java programmer Xtend does not provide much additional value but leads to lots of troubles. E.g. in Java a String array could be initialized with
`final String[] myArray = new String[] {"abc", "def", "ghi"];`
but with Xtend you have to write something like
`val String[] myArray = #["abc","def","ghi"]` which I never remember and always have to look it up on the internet. Also some things are not possible in Xtend, like assigning fixed values to enum literals, etc. 

So I would like to know what you think about Xtend. Do you like and use it or would it be okay for you if we replace Xtend files over time with plain Java classes?

**Comment by timeraider4u** [comment]
Another drawback that I found quite annoying is that you cannot simply exchange code between Xtend and Java source files and, therefore, refactoring becomes annoying (no simple copy&paste).

**Comment by HSorensen** [comment]
I think this is a good discussion to have. But without fully understand how xtend is used by antlr4ide it is hard to qualify if we should use it or not. One thing I would say is it is very impressive what the current code is achieving. Let's try to get documented how xtend is being used and then look at cases where it make sense or not. e.g. the NewProjectWizard is just odd to have as xtend generated code every time, once is of course ok.

**Comment by timeraider4u** [comment]
Well, Xtend is not used by Antlr4IDE, it is consumed during compilation of the Antlr4IDE by the Eclipse Xtend plug-in which consumes this files and writes the corresponding Java files. E.g., whenever you edit _antlr4ide.core/src/main/java/com/github/jknack/antlr4ide/console/Console.xtend_ the file _antlr4ide.core/src/generated/xtend/com/github/jknack/antlr4ide/console/Console.java_ is automatically created by the Xtend builder. This is similar to the principle of how the JDT plug-in works: Whenever a project has a Java nature defined in its _.project_ file and you edit a Java text file, JDT does syntax checking, provides auto-completion, compiles it for you and then generates a corresponding Java class file in the binary output folder.

Xtend itself is independent of the generation happening in the workflow-file _antlr4ide.core/src/main/java/com/github/jknack/antlr4ide/GenerateAntlr4.mwe2_ When you run this workflow it generates the mentioned NewProjectWizard.xtend class file.

**Comment by HSorensen** [comment]
.... see I have a lot to learn:)

**Comment by KristofSzabados** [comment]
For me Xtend was a stopping point.
With ANTLR plugin for eclipse (at sourceforge, support antlr 2.7.6) I could just get the code and fix the issues I had.
With Xtend here, the entry barrier just seemed to be not worth the trouble of fixing inconveniences.

**Comment by timeraider4u** [comment]
@KristofSzabados: Thanks for your contribution to this discussion. It makes a valid point: Mixture of different programming languages in a single project increases confusion and, therefore, increases the entry barrier for new developers.

**Comment by HSorensen** [comment]
I will agree to it is a very steep learning curve, but that said I have manage to fix problems without understanding the xtext/xtend stuff at all. But is has been a lot of trial and error. And as seen with #71 there are cases where I would argue xtext/xtend is being misused.
But even with it's oddness IMO it is pretty impressive what antlr4ide accomplishes and don't underestimate what it takes to make an Eclipse editor with all the features.

I am currently looking at the issues #99, #100, #101 that all have to do with the automated build.
The current version seems to build the g4 files in non-deterministic order. For some time I have had some debug code active that shows the call sequence up to the invocation of the antlr tool.

If you start eclipse with -consolelog option It looks like this:
```
---
--- ToolRunner run file>L/TestStuff/src/testissues.g4<
    com.github.jknack.antlr4ide.generator.ToolRunner.run(ToolRunner.java:64)
    com.github.jknack.antlr4ide.generator.Antlr4Generator.doGenerate(Antlr4Generator.java:146)
    com.github.jknack.antlr4ide.generator.Antlr4Generator.doGenerate(Antlr4Generator.java:99)
    org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:45)
    org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:34)
    org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:564)
    org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:549)
    org.eclipse.xtext.builder.BuilderParticipant.doGenerate(BuilderParticipant.java:534)
    org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:280)
    org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:238)
    org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
    org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
    org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
    org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
    org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
    org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
    org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
    org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
    org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
    org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
    org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
    org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:403)
    org.eclipse.core.internal.resources.Project$1.run(Project.java:551)
    org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
    org.eclipse.core.internal.resources.Project.internalBuild(Project.java:529)
    org.eclipse.core.internal.resources.Project.build(Project.java:112)
    org.eclipse.xtext.ui.preferences.OptionsConfigurationBlock$BuildJob.run(OptionsConfigurationBlock.java:147)
    org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
    ToolRunner validate file>C:\git\antlr4\tool\target\antlr4-4.5.2-SNAPSHOT.jar< version>4.5.2-SNAPSHOT<
```

The question now becomes, who in this call chain has all the resources that need to be built and how can you get control ?

After some googling and looking at xtext source code I found this:
[org.eclipse.xtext.builder.BuilderParticipant.java](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/BuilderParticipant.java)

Looking at build method:
```java
@Override
	public void build(final IBuildContext context, IProgressMonitor monitor) throws CoreException {
		if (!isEnabled(context)) {
			return;
		}

		final List<IResourceDescription.Delta> deltas = getRelevantDeltas(context);
		if (deltas.isEmpty()) {
			return;
		}
....
	protected List<IResourceDescription.Delta> getRelevantDeltas(IBuildContext context) {
		List<IResourceDescription.Delta> result = newArrayList();
		for (IResourceDescription.Delta delta : context.getDeltas()) {
			if (resourceServiceProvider.canHandle(delta.getUri()) && context.isSourceLevelURI(delta.getUri())) {
				result.add(delta);
			}
		}
		return result;
	}
```
All I have to do now is to override the getRelevantDeltas method.
Which takes us back to the antlr4ide source code. A quick search for buildparticipant

Which let me to
```java
package com.github.jknack.antlr4ide.ui;
public abstract class AbstractAntlr4UiModule extends DefaultUiModule { 
...
	// contributed by org.eclipse.xtext.generator.generator.GeneratorFragment
	public Class<? extends org.eclipse.xtext.builder.IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
		return org.eclipse.xtext.builder.BuilderParticipant.class;
	}
```
And I remembered this one:
```java
package com.github.jknack.antlr4ide.ui;
public class Antlr4UiModule extends com.github.jknack.antlr4ide.ui.AbstractAntlr4UiModule { ... }
```
so now we are back in pure java world and next steps are relatively straight forward:
- Add override of `bindIXtextBuilderParticipant()`
- Create and use a new class Antlr4BuilderParticipant
- Determine logic for proper build sequence

```java
package com.github.jknack.antlr4ide.ui;
	public Class<? extends org.eclipse.xtext.builder.IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
		return com.github.jknack.antlr4ide.ui.builder.Antlr4BuilderParticipant.class;
	}
```
and
```java
package com.github.jknack.antlr4ide.ui.builder;
import java.util.List;
import org.eclipse.core.resources.IBuildContext;
public class Antlr4BuilderParticipant extends org.eclipse.xtext.builder.BuilderParticipant {

	@Override
	protected List<org.eclipse.xtext.resource.IResourceDescription.Delta> getRelevantDeltas(IBuildContext context) {
		List<org.eclipse.xtext.resource.IResourceDescription.Delta> result = super.getRelevantDeltas(context);
		int i=0;
		for (org.eclipse.xtext.resource.IResourceDescription.Delta delta : result) {
				System.out.println(">>> Antlr4BuilderParticipant getRelevantDeltas ["+i+"]>"+delta.getUri()+"<");
				i++;
		}
		return result;
	}
}
```

and voila:
```
>>> Antlr4BuilderParticipant getRelevantDeltas [0]>platform:/resource/TestStuff/src-import/imports/B.g4<
>>> Antlr4BuilderParticipant getRelevantDeltas [1]>platform:/resource/TestStuff/src/testissues.g4<
>>> Antlr4BuilderParticipant getRelevantDeltas [2]>platform:/resource/TestStuff/issue154/testissue154.g4<
>>> Antlr4BuilderParticipant getRelevantDeltas [3]>platform:/resource/TestStuff/src-import/imports/A.g4<
>>> Antlr4BuilderParticipant getRelevantDeltas [4]>platform:/resource/TestStuff/src-import/testissue.g4<
```

The next step is really to write the logic that determines the build sequence.

**Comment by HSorensen** [comment]
I started to look at #166 but unless I am missing something, I don't see why to do the xtend/xtext dance for these:
```java
package com.github.jknack.antlr4ide.ui.preferences;
```
Converting this to java is straight forward but are there any reason to use the xtext packages at all.

**Comment by HSorensen** [comment]
Came across a tutorial about xtext and xtend:
http://xtextcasts.org/episodes/21-preference-page

**Comment by HSorensen** [comment]
I have been thinking quite a bit over this.
On the one hand xtext/xtend generates fair amount of useful code for the eclipse editor
but on the other hand I see little value in actually code anything substantial in xtend.

I looked at recreating the eclipse config/preference pages in java, but it seems next to impossible to untangle the current usage of xtext/xtend.

I would like some feedback to this idea:
- Use xtext/xtend to generate the basic editor
- Use Java for anything else

I now have a very basic(*) xtext grammar and will setup a separate branch for this development effort.
Thoughts ?

(*) Basic grammar is relative. There is a need for an external lexer to handle some of the specific language constructs such as nested braces and support for native languages. But I have a prototype working.

**Comment by timeraider4u** [comment]
Well it is possible to get rid of all Xtend files by first replacing all non-generated (manually created) xtend files by hand from xtend to Java, then delete all xtend files from the project, setting `var generateXtendStub = true` to false in `antlr4ide.core/src/main/java/com/github/jknack/antlr4ide/GenerateAntlr4.mwe2`and replacing some of the fragments (e.g., `fragment = validation.ValidatorFragment auto-inject {` with `fragment = validation.JavaValidatorFragment auto-inject {`) in the workflow file.
Then the xtext generation will never ever create xtend stubs again. Only pure Java files...

Problem is how to migrate all functionality that is now stored inside the xtend files to Java. Also (as already mentioned above) some xtend files are not generated by the mwe2 worksflow It is possible to migrate all functionality from xtend syntax to Java but it takes some time and you have to be careful to not forget to migrate any file(s).

**Comment by timeraider4u** [comment]
To get a list of all generated files and all non-generated (created with **File->New->Other->Xtend->Xtend Class** in Eclipse IDE), execute the following command list:
```bash
git reset --hard
git clean -d -f -x
mvn clean install
mvn clean install
git clean -d -f -x
find . -name "*.xtend" | sort > ../all-xtend-files.txt
find . -name "*.xtend" -exec rm {} \;
mvn clean generate-sources
find . -name "*.xtend" | sort > ../generated-xtend-files.txt
diff ../generated-xtend-files.txt ../all-xtend-files.txt > ../non-generated-xtend-files.txt
```

**Comment by timeraider4u** [comment]
By the way: The files in the non-generated files list  can be migrated one by one, the ones in the generated list have to be migrated all at once.

**Comment by HSorensen** [comment]
@timeraider4u could you include the list you already created ?

I looked at converting some of the xtend files to java but in some cases I think it is better to rethink this completely.
If we want to keep xtext and the mwe2 workflow it should be able to build with current version of xtext.
I would rather do something like keep xtext/mwe2 and create separate plugin projects for anything that we create by hand. Keep a clear separation between generated projects and manual projects.

Let me create a branch so we can try some of these ideas.

**Comment by timeraider4u** [comment]
Here you are:
- https://github.com/antlr4ide/antlr4ide-dev-stuff/blob/master/all-xtend-files.txt
- https://github.com/antlr4ide/antlr4ide-dev-stuff/blob/master/generated-xtend-files.txt
- https://github.com/antlr4ide/antlr4ide-dev-stuff/blob/master/non-generated-xtend-files.txt

**Comment by timeraider4u** [comment]
Problem with moving files into separate plugins is that we might easily run into circular dependencies :-(. I know that converting some files from xtend to Java is a huge amount of work but I cannot remember exactly what the problems were. I will have to take a close look again and report back then.

**Comment by HSorensen** [comment]
With the amount of customization needed one question remain: does the xtext/mwe2 generator provide enough value of writing the editor using the native eclipse api ?

**Comment by timeraider4u** [comment]
Pardon me, but I am not getting the meaning of your last post.

Anyway, I should state that the files in https://github.com/antlr4ide/antlr4ide-dev-stuff/blob/master/generated-xtend-files.txt are only partially generated. When for the first time executing a MWE2 workflow, Xtext generates some additional files, like Antlr4Generator.xtend. Whenever you change these files, your customizations will remain as they are. Xtext will not touch your customizations. Xtext will only re-generate the missing files with the default stubs whenever some of these files are deleted, e.g., if you delete Antlr4Generator.xtend running the MWE2 workflow will re-generate a file with the same name containing a generator stub.

That's why all xtend files in the generated list would have to be migrated at once (because otherwise you would end-up with duplicated classes where one contains only a stub file and the other contains the customizations).

**Comment by HSorensen** [comment]
What I tried to say: should we rewrite the eclipse editor using the eclipse API only without any of the generated code.

**Comment by timeraider4u** [comment]
Well, I would not recommend to delete the generated code as it is part of the Xtext framework and it would require a huge amount of additional work to also implement functionality provided by classes of the Xtext framework.

But thanks to you I now got a new idea how it would be possible to separate the generated code stubs and our customizations: For each generated class we also create a customization class, e.g., for Antlr4Formatter.xtend we could create a class Antlr4FormatterCustom.java. We then refactor the code from one class to the other until only the stub and method calls to our customizations remain inside Antlr4Formatter.xtend. This way the migration from Xtend to Java can also be done incrementally.

**Comment by timeraider4u** [comment]
So, if we would merge #185 then there would be 
```bash
cd ../antlr4ide-dev-stuff && echo "$(cat all-xtend-files.txt | wc -l) - $(cat converted-xtend-files.txt | wc -l)" | bc
61
```
files left to convert from Xtend to Java.

**Comment by HSorensen** [comment]
So I tried to do an Editor that uses the native Eclipse API. 

[see this prototype in the antlr4ide-dev-stuff](https://github.com/antlr4ide/antlr4ide-dev-stuff/pull/1)

This is doable, but still a lot of work.

With this things become much more transparent and understandable. For example configuring of syntax highlights:

```java
	/**
	 * Map Antlr token types to eclipse text attribute tokens
	 */
	static {
	   hilite = new HashMap<Integer, IToken>();
	   // Statements
	   hilite.put(ANTLRv4Lexer.FRAGMENT, stmtTextToken);
	   hilite.put(ANTLRv4Lexer.CHANNELS, stmtTextToken);
	   hilite.put(ANTLRv4Lexer.PARSER,   stmtTextToken);
	   hilite.put(ANTLRv4Lexer.LEXER,    stmtTextToken);
	   hilite.put(ANTLRv4Lexer.OPTIONS,  stmtTextToken);
	   hilite.put(ANTLRv4Lexer.TOKENS,   stmtTextToken);
	   hilite.put(ANTLRv4Lexer.GRAMMAR,  stmtTextToken);
	   hilite.put(ANTLRv4Lexer.IMPORT,   stmtTextToken);

	   // Constants
	   hilite.put(ANTLRv4Lexer.INT,            constTextToken);
	   hilite.put(ANTLRv4Lexer.STRING_LITERAL, constTextToken);
	   
	   // Comments
	   hilite.put(ANTLRv4Lexer.DOC_COMMENT,   commentTextToken);
	   hilite.put(ANTLRv4Lexer.BLOCK_COMMENT, commentTextToken);
	   hilite.put(ANTLRv4Lexer.LINE_COMMENT,  commentTextToken);
	   
	   // References
	   hilite.put(ANTLRv4Lexer.TOKEN_REF, lexerRuleTextToken);
	   hilite.put(ANTLRv4Lexer.RULE_REF,  parserRuleTextToken);
	}
```

This is still a prototype, but I am considering creating a new repository for this approach.

Comments ?

**Comment by HSorensen** [comment]
I have created  WIP repository of the editor using native eclipse API:
https://github.com/antlr4ide/antlr4ide-eclipse

Note, current state is only for demonstrating the feasibility of using the native eclipse API. It is not ready for any real usage.

**Comment by timeraider4u** [comment]
Closed in favour of https://github.com/antlr4ide/antlr4ide/issues/186
