### ISSUE TITLE
Move gh-pages into its own repository

### ISSUE THREAD

**Issue by timeraider4u** [antlr4ide/antlr4ide#164]
Dear all,
should we move the files of the gh-pages branch into a separate repository? I have seen that several organisations use an independent repo for hosting the Github web-pages. So I would like to know what you think about it...

**Comment by HSorensen** [comment]
I think we can remove the branch all together. Is there anything in the branch we need to keep?

**Comment by HSorensen** [comment]
Also remove the 0.1.0 branch?

**Comment by timeraider4u** [comment]
I do not know anything about the 0.1.0 branch. Who created it? Last commit was in 2014 and it is 163 commits behind with no none-merged changes. So I would guess we could also get rid of it.

**Comment by timeraider4u** [comment]
The gh-pages commit contains data for the web-pages (hosted on GitHub, see also Github pages) which can be viewed at http://antlr4ide.github.io/antlr4ide/ at the moment. Maybe we would like to modify it at some point and make use of the updated version then...?

**Comment by timeraider4u** [comment]
Therefore, I would propose to get rid of the gh-pages branch, but instead of simply removing the files, moving them to a separate repo.

**Comment by HSorensen** [comment]
All the content is already merged to the master, so I am not sure of the value of keeping the two branches.

**Comment by HSorensen** [comment]
Also last change were 3 years ago. Let's clean them up by removing them.

**Comment by timeraider4u** [comment]
I have found that a lot of files from the gh-pages branch are still available in the updates folder from the master branch. So we could remove the gh-pages branch at all and maybe move the updates folder to its own repository or something like that.

**Comment by timeraider4u** [comment]
Note: I have deleted the 0.1x branch now as it is not needed any more. If someone has objections against it in the next 2 weeks, I can still restore it from a local copy on my workstation.

**Comment by HSorensen** [comment]
can you explain what the gh-pages branch is used for ?
I don't think it is being used, but I could easy have missed it if it were.

**Comment by timeraider4u** [comment]
A gh-pages branch can be used to create a web-site with API-documentation or a web-page for the corresponding repository. 

E.g., when you open https://github.com/antlr4ide/antlr4ide/tree/gh-pages you will see an index.html file inside of it together with a folder named images. When you now navigate to http://antlr4ide.github.io/antlr4ide/ you can see that instead of the content of the git repository, Github presents the web-content.

**Comment by timeraider4u** [comment]
More information about Github pages can also be found at https://pages.github.com/

**Comment by timeraider4u** [comment]
gh-pages can be compared to a FTP-server: You upload files to a specific directory (in this case the branch named gh-pages) and Github presents them as web pages like a web-server would do for your FTP-directory.

**Comment by arifogel** [comment]
I'm not sure what they WERE using gh-pages for, but @jknack told me someone
at some point tried to host the marketplace site on github pages
unsuccessfully. Unless there is actual content there that people are using,
I say get rid of it. I am already hosting marketplace releases on a
separate repository in this organization without the use of gh-pages.

**Comment by HSorensen** [comment]
Didn't know about pages, looks interesting.
I think for now we should focus on getting the tool itself to a better state, get the internal workings documented and then maybe there is a path to a product.
I will vote +1 for deleting the gh branch and the pages stuff and let us revisit this once the tool is ready.

**Comment by timeraider4u** [comment]
removed gh-pages by now, therefore, closing this issue.
