### ISSUE TITLE
Error while building in antlr4IDE, though it succeeds from command line.

### ISSUE THREAD

**Issue by bbindra** [antlr4ide/antlr4ide#173]
Getting following error in the latest build. This comes for any grammar file.

ANTLR Tool v4.4 (C:\Users\SURIND~1.BIN\AppData\Local\Temp\antlr-4.4-complete.jar)
businessRulePredicate.g4 -o C:\workspace\businessRulePredicate\target\generated-sources\antlr4 -listener -no-visitor -encoding UTF-8
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

BUILD SUCCESSFUL
Total time: 292 millisecond(s)

**Comment by timeraider4u** [comment]
@bbindra: sounds like a MS Windows <--> Java issue and should be independent of ANTLR4IDE. Maybe your PATH environment is set-up incorrectly. Please also see http://stackoverflow.com/questions/29697543/registry-key-error-java-version-has-value-1-8-but-1-7-is-required and http://stackoverflow.com/questions/8644992/error-registry-key-software-javasoft-java-runtime-environment-currentversion

**Comment by bbindra** [comment]
Got rid of this error, but now I am getting following error:-

Errors occurred during the build.
Errors running builder 'AntlrDT Builder' on project 'businessRulePredicate'.
org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.core.resources.IFolder

**Comment by arifogel** [comment]
What version of eclipse are you using? What are the steps to reproduce?

**Comment by bbindra** [comment]
I am using 

Eclipse IDE for Java Developers

Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200

I get this every time I generate source using "Run As" --> "Generate ANTLR recoginazer" on any grammar.

BTW, thanks @timeraider4u to help resolve the "MS Windows Java issue".

**Comment by arifogel** [comment]
Can you reproduce this behavior with a new project? If so, please provide
all steps to reproduce from scratch, and include a minimal .g4 file that
elicits this behavior.

**Comment by bbindra** [comment]
I further looked at my installation and found that AntlrDT is installed. I uninstalled it and the problem is gone. I think error might be due to AntlrDT.

Thanks for the help!

**Comment by timeraider4u** [comment]
just for the record: AntlrDT is an Eclipse plug-in which can be found at https://marketplace.eclipse.org/content/antlrdt It offers an editor with syntax highlighting, code completion and an outline view - just like Antlr4IDE. As far as I know it has nothing to do with Antlr4IDE - except providing the same functionality. Also the parse tree view looks quite impressive - would be cool to have this feature in Antlr4IDE too ;-).

**Comment by timeraider4u** [comment]
added link to ANTLR development tool comparison in efc0cd7
