### ISSUE TITLE
Possibility to use the -package option

### ISSUE THREAD

**Issue by Krzmbrzl** [antlr4ide/antlr4ide#178]
When using the ANTLR tool from the console I can tell it to put the generated java files in a specific package with the `-package` option.
I really miss that one in the plugin as putting it in by hand can be a lot of work and it shouldn't be too hard tro implement it since you have already implemented som other options.

**Comment by HSorensen** [comment]
Are you generating the same grammar for different packages ?
Otherwise you can use the `@header` construct:
```antlr
@header {
package your.package.naem
}
```

**Comment by Krzmbrzl** [comment]
Alright that should do the trick for me thanks! 
But on my opinion it would still be a good thing to include all antlr options in the Plugin as some people (like me) will be searching for it... 
Or of you don't want to implement each option then you could specify a text field in which the user can enter the parameter for the tool ;)

**Comment by HSorensen** [comment]
ok, point noted.  Closing this for now.
