### ISSUE TITLE
Setting target language

### ISSUE THREAD

**Issue by pbalaga** [antlr4ide/antlr4ide#179]
Hello,

how do I set the target language, so that I can produce something else than .java files?

Thanks

**Comment by Puchaczov** [comment]
Is it really not possible to set destination language? Isn't possible to force somehow editor to add new parameter to command?

**Comment by HSorensen** [comment]
Currently not. You can create a lauch config, but that is a bypass.
Which language are you generating for ?
One problem is testing this. Personally I only use Java, but if you want to
help include this feature into antlr4ide let us know
Henrik

**Comment by pbalaga** [comment]
This is exactly how I got around this - for me it worked well enough. @HSorensen, in what sense is it a bypass? Am I missing something this way?

![image](https://cloud.githubusercontent.com/assets/14298228/22857562/a4541af8-f0a7-11e6-96f7-c0e52d714ebf.png)

**Comment by HSorensen** [comment]
Can the target language be specified inside the g4 source code as an option
?
