### ISSUE TITLE
antlr4 have error when i run it 

### ISSUE THREAD

**Issue by randomnum** [antlr4ide/antlr4ide#183]
I am using antlr4 on eclipse , when I run the antlr4 then this message appare in console antlr
ANTLR Tool vnull (C:\antlr-4.5.3-complete.jar)
Hello.g4 -o C:\Users\EAGLE_EYE\newworkspace\MyParser\target\generated-sources\antlr4 -listener -visitor -encoding UTF-8
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
BUILD SUCCESSFUL
Total time: 109 millisecond(s)

what wrong ?

**Comment by timeraider4u** [comment]
It seems your bug report is missing some information. Can you please add the following information:
1.) Which Java version(s) do have currently installed on your operating system (vendor/version)? Can be found in, for example MS Windows system settings -> programs
2.) Which Java version is specified in your eclipse.ini file (eclipse.ini can be found inside the Eclipse installation folder)?
3.) Which Java version is specified in your Eclipse workbench (inside Eclipse: Window->Preferences->Java->Installed JREs)?

**Comment by timeraider4u** [comment]
No reaction within 28 days, therefore, closing this now.
