### ISSUE TITLE
how I can knew If I have plus or sub node in antlr4?

### ISSUE THREAD

**Issue by randomnum** [antlr4ide/antlr4ide#184]
I am building my ast , I use antlr4 so I write the expression in way to order the expression (+,-,*,/) :
```
expression returns [ASTNode node]
  :  expression ('*'|'/'|'%') expression
  |  t1=expression ('+'|'-') t2=expression 
  ;
```
when I build my ast I write :
`t1=expression ('+'{$node=new Addition($t1.node,$t2.node);}|'-'{$node=new Sub($t1.node,$t2.node);}) t2=expression`

then I have nullpointer exception , so what the right way to write this grammer ?

**Comment by timeraider4u** [comment]
@randomnum Can you please provide a complete example? I am not an ANTLR4 expert but anyway it would be easier to investigate your problem with a running example. You might create a small test repository on Github and just link it.

You might of course also ask your question upstream at https://github.com/antlr/antlr4/issues
