### ISSUE TITLE
Dynamic attribute scope not supported

### ISSUE THREAD

**Issue by sweetnavelorange** [antlr4ide/antlr4ide#61]
References to dynamic rule-scoped attributes are marked as errors in antlr4ide, but generate perfectly valid code from the antlr 4.2.2 command line tooling. For example, given a grammar fragment:

```
decl
    locals [boolean repeating]
    :   typedef=defn qualifier* option? ';'
    ;

qualifier:   'repeating' {$decl::repeating = true;} ;
```

the reference to `$decl` is marked as an error in antlr4ide with the message "unknown attribute reference 'decl' in '$decl'", but code generated from the command line contains the correct interpretation: `((DeclContext)getInvokingContext(2)).repeating =  true;`.

**Comment by rgoulter** [comment]
I don't think this is quite fixed yet on `0a6d`. `$start` and `$ctx` work well. And for rule (say) `qualifier`, `$qualifier` works, but `$decl` scope (as per above example) doesn't.
