### ISSUE TITLE
[Feature Request] Show source of generated files in IDE

### ISSUE THREAD

**Issue by morpheus133** [antlr4ide/antlr4ide#70]
Hi!
In the antlr3 ide eclipse shows for the generated files, from what file it was generated from.
Is it possible to add this feature for this also?

**Comment by HSorensen** [comment]
How does antlr3ide show this ?
Would a comment in the generated file do ?

**Comment by morpheus133** [comment]
Hi,
In this picture you see a part of it:
[http://antlrv3ide.sourceforge.net/resources/screenshotfull.png](http://antlrv3ide.sourceforge.net/resources/screenshotfull.png)

After the two .tokens and Tree.java it is visible that it was generated.

The best solution can be something like this:
http://stackoverflow.com/questions/25412042/how-eclipse-show-the-name-of-the-file-generated-from

But i havent got time to dig deeper, because i was moved for other projects.

**Comment by HSorensen** [comment]
You mean a notice after the generated files to show which file were the source for the generation:
![image](https://cloud.githubusercontent.com/assets/5041461/20459193/d883cdfe-ae6d-11e6-8db6-1b2d738c9f23.png)

like the Expr.g in the red box?
