### ISSUE TITLE
Output Directory Bug

### ISSUE THREAD

**Issue by hendryau** [antlr4ide/antlr4ide#80]
I want to put my generated grammar files in <code>./antlr-generated/antlr/generated</code>. I have 3 grammars in my project. The first two grammars' generated code goes into <code>./antlr-generated/antlr/generated/antlr/generated</code>. The last grammar's generated code goes to <code>./antlr-generated/antlr/generated</code>

![output directory bug](https://cloud.githubusercontent.com/assets/3278649/3703834/c6ba9d70-140d-11e4-981f-62f6fe9d62a2.png)

**Comment by HSorensen** [comment]
You can use the @header { package ... } or for special processing you might have to using ANT to control your build.
Closing this for now.
