### ISSUE TITLE
"Resource is currently edited in another editor" every time I save

### ISSUE THREAD

**Issue by vishuv** [antlr4ide/antlr4ide#89]
Eclipse shows a dialog box "The resource is currently edited in another editor. Do you want to continue?" every time I save my grammar file.
![screenshot from 2014-09-17 22 04 00](https://cloud.githubusercontent.com/assets/284143/4314552/bca1bc02-3ee1-11e4-81da-67aa523e5617.png)
Any hint on how to fix it?
BTW its eclipse Luna

**Comment by rulatir** [comment]
How do I obtain the updated version of Xtext with this bug fixed? It doesn't get installed by just running "Check for updates...".

Or does the fix mentioned here only fix it for a particular editor? I have this problem with the LESS editor. Will it be fixed by this fix?
